### PR TITLE
Update acorn to the latest version

### PR DESCRIPTION
**Pull request by fredj**
And set the ecma version to 6 to allow 6 to 5 transpilation (using `language_in` and `language_out` options)

### CODE REVIEW

**Comment by fredj** [comment]
ecma 5 is a subset of ecma 6; this change is backward compatible

**Comment by elemoine** [comment]
This looks good to me.

**Comment by fredj** [comment]
Thanks for the review.
FYI I'm using it to play with es6 in ol3: https://github.com/openlayers/ol3/compare/master...fredj:es6

**Comment by elemoine** [comment]
> FYI I'm using it to play with es6 in ol3

Nice!

**Pull request merged**
