### PR TITLE
Upgrade closure compiler and library

### PR DESCRIPTION
**Pull request by fredj**
The closure-library project now release a version with the same version as the closure-compiler

### CODE REVIEW

**Comment by fredj** [comment]
Thanks for any review

**Comment by fredj** [comment]
A new compiler version was released yesterday, updated

**Comment by ahocevar** [comment]
Looks good, please merge.

**Comment by fredj** [comment]
I've just checked this version with ol3 and it doesn't build (new errors)

**Comment by fredj** [comment]
All the ol3 issue have been fixed

**Pull request merged**
