### PR TITLE
Drop Node.js versions prior to 4

### PR DESCRIPTION
**Pull request by fredj**
See https://github.com/openlayers/closure-util/pull/199#issuecomment-237168488

### CODE REVIEW

**Comment by probins** [comment]
I think this makes sense. Node is dropping LTS for 0.12 at the end of the year anyway https://github.com/nodejs/LTS/

**Comment by fredj** [comment]
And we should tests version 6 instead of 5

**Comment by ahocevar** [comment]
Looks good. And yes, better to test with Node 6 rather than 5.

**Comment by fredj** [comment]
Thanks for the review

**Pull request merged**
