### PR TITLE
Upgrade closure compiler version (v20150315)

### PR DESCRIPTION
**Pull request by fredj**
Changelog: https://github.com/google/closure-compiler/wiki/Releases#march-15-2015-v20150315

### CODE REVIEW

**Comment by fredj** [comment]
Hold on; there's an error with ol3 ...

**Comment by fredj** [comment]
Depends on https://github.com/openlayers/ol3/pull/3433

**Comment by elemoine** [comment]
@fredj can this be merged?

**Comment by fredj** [comment]
Yes, it's ready

**Comment by elemoine** [comment]
Please merge.

**Pull request merged**
