### PR TITLE
Upgrade closure compiler version (v20150729)

### PR DESCRIPTION
**Pull request by fredj**
https://github.com/google/closure-compiler/wiki/Releases#july-29-2015-v20150729

### CODE REVIEW

**Comment by elemoine** [comment]
Do OpenLayers compile with this?

**Comment by fredj** [comment]
Depends on https://github.com/openlayers/ol3/pull/4027

**Comment by elemoine** [comment]
Is this ready for merging?

**Comment by fredj** [comment]
re-testing now

**Comment by elemoine** [comment]
Thanks @fredj. This is for https://github.com/camptocamp/ngeo/issues/306: ngeo and ngeo app builds fail at compilation time because of changes in the angular externs. My guess is that these changes depend on recent version of the compiler.

**Comment by fredj** [comment]
ol3 compiles with  this version.
tested with:
```diff
diff --git a/closure-util.json b/closure-util.json
index 1568b29..efbeda5 100644
--- a/closure-util.json
+++ b/closure-util.json
@@ -1,3 +1,4 @@
 {
+  "compiler_url": "http://dl.google.com/closure-compiler/compiler-20150729.zip",
   "library_url": "https://github.com/google/closure-library/archive/a5f9b8a.zip"
 }
```

and `make ci`

**Comment by elemoine** [comment]
So I'd suggest that we merge this, publish a new version of closure-util, and update closure-util in ol3. I can take care of the rest when this is merged.

**Comment by fredj** [comment]
version 1.6.2 or 1.7.0 ?

**Comment by elemoine** [comment]
What do we usually do when upgrading the compiler?

**Comment by fredj** [comment]
"minor" update -> 1.7.0

**Comment by elemoine** [comment]
Are you publishing 1.7.0 or should I do it?

**Comment by fredj** [comment]
package published: https://www.npmjs.com/package/closure-util

**Pull request merged**
