### PR TITLE
Address windows issues

### PR DESCRIPTION
**Pull request by tschaub**
This gets the `closure-util` server working on Windows.

### CODE REVIEW

**Comment by elemoine** [comment]
@tschaub, can this be merged? It looks good to me.

**Comment by tschaub** [comment]
Hmmm.   I just sat down with a Windows VM the other day and found some other issues.  But I think this one is still valid.

**Comment by elemoine** [comment]
FYI, with this patch, for the moment, closure-util#master works for us on Windows! Thanks.

**Comment by elemoine** [comment]
It looks like I spoke too fast. It looks like the loader works in Chrome but not in Firefox (on Windows). I'll see if I can provide more detail.

**Comment by elemoine** [comment]
For some reason I'm seeing url-encoded paths in the generated `src`'s in Firefox. E.g.

```
http://localhost:3000/@C:%5CUsers%5Cbarris%5CDesktop%5Cclosure-project2%5Cnode_modules%5Cclosure-util%5C.deps%5Clibrary%5Cfc6e5e05ebc150be8bb214d2a3fd77798975a6b2%5Cclosure%5Cgoog%5Cbase.js
```

**Comment by bartvde** [comment]
yeah I am seeing the same thing, the loader works in Chrome but not in FF on my Windows VM

**Pull request merged**
