### PR TITLE
Escape the double quotes around compile flag values

### PR DESCRIPTION
**Pull request by fredj**

### CODE REVIEW

**Comment by elemoine** [comment]
I am also having problems with closure-util 1.6. See https://github.com/openlayers/ol3/pull/4028. Maybe it's related to your PR.

**Comment by elemoine** [comment]
Yep, that fixes it. We could also use single quotes in ol3's umdWrapper, no?

**Comment by fredj** [comment]
> We could also use single quotes in ol3's umdWrapper, no?

I didn't tried but it should work.

**Comment by elemoine** [comment]
I think you can still merge that. And I think it would make sense to release 1.6.1. Would you do that?

**Comment by fredj** [comment]
> And I think it would make sense to release 1.6.1. Would you do that?

I will do it

**Pull request merged**
