### PR TITLE
Properly handle null in like util function

### PR DESCRIPTION
**Pull request by gberaudo**
Comparaison to null was not working in the case of an object:
"TypeError: Cannot convert undefined or null to object".

### CODE REVIEW

**Comment by gberaudo** [comment]
Any review?

**Comment by gberaudo** [comment]
Is there something wrong or unclear with this PR?
@tschaub, @fredj, this is blocking openlayers/ol3#5341. It would be great if one of you had some time to review this PR so that I can go forward.

**Comment by fredj** [comment]
LGTM

**Comment by gberaudo** [comment]
Thanks.

**Pull request merged**
